### ISSUE TITLE
Interested in adding nodenv-nvmrc to nodenv's brew tap?

### ISSUE THREAD

**Issue by jasonkarns** [ouchxp/homebrew-nodenv#1]
Would you open to migrating the nodenv-nvmrc formula to the nodenv org's homebrew tap at https://github.com/nodenv/homebrew-nodenv ?

**Comment by ouchxp** [comment]
Wow, very sorry I just saw this comment after so long. It would be my plasure to migrate! I'll create a PR soon!

**Comment by ouchxp** [comment]
PR created https://github.com/nodenv/homebrew-nodenv/pull/92
